### ISSUE TITLE
License/Permissions to use this repository for Educational Program

### ISSUE THREAD

**Issue by PhilAzeredo** [tallis/SAE-J2735-Python#1]
Hi Rui,

I sent you a brief LinkedIn message about this, but in case if you don't check that platform (which I would totally understand):
Would you be willing to post an open-source license in the readme of this repository and/or grant permission to use it and expand on it?
I'd be happy to discuss further if you wish.

**Comment by tallis** [comment]
License added: https://github.com/tallis/SAE-J2735-Python/commit/eeb68eedab3819b5df2152e3dbf1968dac08878f
