### ISSUE TITLE
Example to decode SAE J2735

### ISSUE THREAD

**Issue by glakshay** [tallis/SAE-J2735-Python#2]
Hello,

I am trying to use your repository to decode the SAE J2735 PER data but I am not sure how it works. Can you please provide a short description on how to use the work like how to decode a particular file?

Thank you
Lakshay

**Comment by tallis** [comment]
Documentation and inline comments added: https://github.com/tallis/J2735-python/commit/9a1859103723cf847d07dd39439df7d4e1464d64 

Hope it's clearer now. Thanks!
